include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    todo: info
linter:
  rules:
    - always_put_required_named_parameters_first
    - lines_longer_than_80_chars
    # - public_member_api_docs
    - prefer_single_quotes
    - sort_child_properties_last
    - sort_constructors_first
    - sort_pub_dependencies
